<a href="https://colab.research.google.com/github/doloresgarro/Deep-Learning/blob/main/Practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **REPASO DE PYTHON**

---


### **Ejercicio 1**
*Utilizando los constructores para cada tipo de dato genere códigos de ejemplo y recórralos imprimiendo sus valores.*

In [ ]:
# lista
nums = [1, 2, 3, 4, 5]
# Imprimo lista
nums[:5]

[1, 2, 3, 4, 5]

In [ ]:
# tupla --> similar a una lista pero no se puede modificar elementos dentro de ella,
# se define entre ()
numsT = (1, 2, 3, 4, 5)
print(numsT) #imprime con ()
print(nums) # imprime con []

(1, 2, 3, 4, 5)
[1, 2, 3, 4, 5]


In [ ]:
# strings
palabras = "Hola Doloresssssssssss"
print(palabras)
print(len(palabras))
print(type(palabras))


Hola Doloresssssssssss
22
<class 'str'>


In [ ]:
# conjuntos
conj1 = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
conj2 = set([0, 2, 4, 6, 8,10, 12, 14, 16, 18, 20])

print('Conjunto 1')
print(conj1)
print('Conjunto 2')
print(conj2)
print()

# si cambio el orden o duplico un numero dentro del conjunto --> al imprimir está ordenado y no aparece el dato repetido
conj1 = set([1, 3, 5, 2, 6, 7, 4, 8, 9, 10])
conj2 = set([0, 2, 4, 4, 6, 8,10, 12, 14, 16, 18, 20])

print(conj1)
print(conj2)
print()

# elem que estan
print('Elementos que estan en el conj1 y no estan en el conj2')
print(conj1 - conj2) # --> elem q estan en el conj1 que no estan en el conj2


print('Elementos que estan en el conj2 y no estan en el conj1')
print(conj2 - conj1) # --> elem q estan en el conj2 que no estan en el conj1

# intersección --> elem q estan en ambos conjuntos
print('Intersección')
print(conj1 & conj2)

# union --> elems de ambos conjuntos
print('Unión')
print(conj1 | conj2)


Conjunto 1
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
Conjunto 2
{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20}

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20}

Elementos que estan en el conj1 y no estan en el conj2
{1, 3, 5, 7, 9}
Elementos que estan en el conj2 y no estan en el conj1
{0, 12, 14, 16, 18, 20}
Intersección
{2, 4, 6, 8, 10}
Unión
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20}


In [ ]:
# diccionario
persona = {'Nombre' : 'Dolores', 'Apellido' : 'Garro', 'Edad' : 23}

print('El nombre de la persona es: ')
print(persona['Nombre'])

print('Garro' in persona) # da falso porque busca una key
print('Apellido' in persona)

print(len(persona))

El nombre de la persona es: 
Dolores
False
True
3


### **Ejercicio 2**
*Genere el código necesario para recorrer simultáneamente 2 listas con la misma cantidad de elementos e imprima los mismos utilizando un único for (tip: función zip).*


In [ ]:
lista1 = [1, 2, 3]
lista2 = ['Juan', 'Valentina', 'Dolores']

list(zip(lista1, lista2))

[(1, 'Juan'), (2, 'Valentina'), (3, 'Dolores')]

### **Ejercicio 3**

*Implemente una función que a partir de la lista que recibe cómo parámetro, retorne una nueva lista sin elementos
repetidos. Compruebe su correcto funcionamiento.*


In [ ]:
def funcion(l1):
  l2 = list(set(l1)) #convierto en conjunto --> creo q primero convierte l1 en conjunto y dsp lo vuelve a convertir a lista
  return l2

In [ ]:
l1 = [1, 3, 3, 4]
print(l1)

print('Sin repetidos: ')
print(funcion(l1))




[1, 3, 3, 4]
Sin repetidos: 
[1, 3, 4]


### **Ejercicio 4**
*Implemente una función que calcule la distancia entre 2 puntos (2D). Utilice la función sqrt del paquete math para
implementarla y compruebe el correcto funcionamiento de la misma.*


In [ ]:
import math
x1 = 4 # esta bien sin guardar cada punto en una lista?
x2 = 2
y1 = 4
y2 = 2
d = math.sqrt(((x1-x2)**2)+((y1-y2)**2))
print(d)

2.8284271247461903


### **Ejercicio 5**
*Investigue y escriba código que demuestre el funcionamiento de los “slices” en listas*

In [ ]:
numeros = [8, 10, 4, 7, 3, 3, 23, 9]
print(numeros[:8]) #imprime todos elementos
print(numeros[:])
print(numeros[3:6]) #imprime elementos desde pos 3 hasta pos 5
print(numeros[0:4])

[8, 10, 4, 7, 3, 3, 23, 9]
[8, 10, 4, 7, 3, 3, 23, 9]
[7, 3, 3]
[8, 10, 4, 7]


# **BIBLIOTECA NUMPY**
---

# **Ejercicio 1**


*Practique la creación de vectores, matrices y tensores y responda:*

------------------------------------

*● ¿Qué diferencias hay entre los constructores, array, empty, full, zeros, ones, identity?*

**array** --> crea un array a partir de la lista o tupla lista y devuelve una referencia a el.

**empty** --> crea y devuelve una referencia a un array vacío

**full** --> crea y devuelve una referencia a un array cuyos elementos son todos valor.

**zeros** --> crea y devuelve una referencia a un array cuyos elems son todos ceros.

**ones** --> crea y devuelve una referencia a un array cuyos elems son todos unos.


**identity** -->  Crea y devuelve una referencia a la matriz identidad.


----------------------------------------


*● ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por defecto?¿Es siempre el mismo?*

Los tipos de datos que pueden utilizarse son --> int, float, complex
El tipo de dato que se toma por defecto es el float.

----------------------------------

*● ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?*
- np.randint(a,b) --> devuelve un número entero comprendido entre a y b (ambos inclusive) de forma aleatoria.

- np.randrange(a,b,salto) --> genera números enteros aleatorios comprendidos entre a y b separados entre sí con un salto.

- np.random() --> devuelve un float comprendido entre [0.0 y 1.0)

- np.uniform(a,b) --> devuelve un float aleatorio comprendido entre a y b (ambos inclusive).

- np.sample(conjunto, n) --> Esta función devuelve n elementos aleatorios de la secuencia conjunto

In [3]:
import numpy as np

In [29]:
# creo e imprimo vector
v = np.array([1, 2, 3])
print('vector: ')
print (v)

print()

# creo e imprimo matriz
m = np.array([(1, 2, 3), (4, 5, 6)])
print('matriz: ')
print(m)

print()

# creo e imprimo matriz de unos --> indico filas y columnas
unos = np.ones((3, 4))
print('matriz de unos: ')
print(unos)

print()

# creo e imprimo matriz de ceros --> indico filas y columnas
ceros = np.zeros((3, 4))
print('matriz de ceros: ')
print(ceros)

print()

# creo e imprimo matriz de nums aleatorios --> indico filas y columnas
aleatorios = np.random.random((2, 2))
print('matriz de nums random: ')
print(aleatorios)


print()

# creo e imprimo matriz vacia --> indico filas y columnas
vacia = np.empty((3, 2))
print('matriz vacia: ')
print(vacia) # no me imprime bien

print()

# creo e imprimo matriz con un solo valor en todas las posiciones
full = np.full((3, 2), 8)
print('matriz: ')
print(full)

print()

# creo e imprimo matriz con valores equiespaciados
espacio1 = np.arange(0, 30, 5) # --> valores desde 0 hasta 30 con un paso de 5
espacio2 = np.linspace(0, 2, 5) # --> matriz con 5 valores entre 0 y 2
print('matriz 1: ')
print(espacio1)
print('matriz 2: ')
print(espacio2)

# creo e imprimo matriz identidad
identidad1 = np.eye(4, 2) #
print('matriz identidad: ')
print(identidad1)

identidad2 = np.identity(2)
print('matriz identidad: ')
print(identidad2)

print()


vector: 
[1 2 3]

matriz: 
[[1 2 3]
 [4 5 6]]

matriz de unos: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

matriz de ceros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

matriz de nums random: 
[[0.49188448 0.31212973]
 [0.95256291 0.85145225]]

matriz vacia: 
[[4.e-323 4.e-323]
 [4.e-323 4.e-323]
 [4.e-323 4.e-323]]

matriz: 
[[8 8]
 [8 8]
 [8 8]]

matriz 1: 
[ 0  5 10 15 20 25]
matriz 2: 
[0.  0.5 1.  1.5 2. ]
matriz identidad: 
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]
matriz identidad: 
[[1. 0.]
 [0. 1.]]



# **Ejercicio 2**



Investigue y ejemplifique las funciones relacionadas al tamaño de los arrays de Numpy:

---------------------------------------
● ¿Para qué sirven las funciones shape, len, ndim, size?

- np.shape : Devuelve una tupla con las dimensiones del array.

- np.size : Devuelve el número de elementos del array.  

- np.len: Devuelve la cantidad de elementos de una matriz (m --> unidimensional)

- np.ndim : Devuelve el número de dimensiones del array.

- np.dtype: Devuelve el tipo de datos de los elementos del array.

---------------------------------------
● ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por defecto?¿Es siempre el mismo?


---------------------------------------
● ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?

In [39]:
 # para conocer las dimensiones de la matriz --> filas
a = np.array([(1, 2, 3), (4, 5, 6)])
print('La dimension de la matriz identidad 1 es:')
print(a.ndim)

print()

# para conocer el tipo de dato de los elem y el tamaño almacenados en la matriz
a = np.array([(1, 2, 3)])
print('Tipo de dato de los elems de la matriz a: ')
print(a.dtype)

print()

# para conocer el tamaño y y forma de la matriz
a = np.array([(1, 2, 3, 4)])
print('Tamaño de la matriz a: ')
print(a.size)
print('Forma de la matriz a: ')
print(a.shape)

print()

# para cambiar la forma de la matriz
a = np.array([(8, 9, 10), (11, 12, 13)])
print('matriz inicial')
print(a)
print('matriz modificada: ')
a = a.reshape(3, 2)
print(a)

# para seleccionar un elem de la matriz
a = np.array([(8, 9, 10), (11, 12, 13)])
print('matriz en la fila 0 columna 2')
print(a[0, 2])

# para imprimir todos los elem de una fila la matriz
a = np.array([(8, 9, 10), (11, 12, 13)])
print('todos los elementos de la matriz en la columna 2: ')
print(a[0:, 2])


La dimension de la matriz identidad 1 es:
2

Tipo de dato de los elems de la matriz a: 
int64

Tamaño de la matriz a: 
4
Forma de la matriz a: 
(1, 4)

matriz inicial
[[ 8  9 10]
 [11 12 13]]
matriz modificada: 
[[ 8  9]
 [10 11]
 [12 13]]
matriz en la fila 0 columna 2
10
todos los elementos de la matriz en la columna 2: 
[10 13]


# **Ejercicio 3**

*Practique funciones de agregación (sum, min, max, etc.) sobre vectores, matrices y tensores. Enumere y pruebe todas las funciones que encuentre y responda:*

*● ¿Estas funciones se aplican a todos los datos del array o pueden realizarse sobre dimensiones particulares? Ejemplifique.*

In [61]:
# encontrar valor minimo, maximo y la suma
a = np.array([2, 4, 8])
print('El valor minimo de matriz es: ')
print(np.min(a))
print('El valor máximo de matriz es: ')
print(np.max(a))
print('La suma de los valores de la matriz es: ')
print(np.sum(a))

print()

# encontrar raiz cuadrada y desviación estándar
a = np.array([(1, 2, 3), (3, 4, 5,)])

print('La raiz cuadrada de los valores de la matriz es: ')
print(np. sqrt(a))
print()
print('La desviación estándar de los valores de la matriz es: ')
print(np.std(a))


print()

# calcular suma, resta, multiplicación y división de dos matrices
x = np.array([(1, 2, 3), (4, 5, 6)])
y = np.array([(1, 2, 3), (4, 5, 6)])

print('Suma de matrices')
print(x+y)

print()

print('Resta de matrices')
print(x-y)

print()

print('Multiplicación de matrices')
print(x*y)

print()

print('Multiplicación de matrices')
print(x/y)

print()

El valor minimo de matriz es: 
2
El valor máximo de matriz es: 
8
La suma de los valores de la matriz es: 
14

La raiz cuadrada de los valores de la matriz es: 
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]

La desviación estándar de los valores de la matriz es: 
1.2909944487358056

Suma de matrices
[[ 2  4  6]
 [ 8 10 12]]

Resta de matrices
[[0 0 0]
 [0 0 0]]

Multiplicación de matrices
[[ 1  4  9]
 [16 25 36]]

Multiplicación de matrices
[[1. 1. 1.]
 [1. 1. 1.]]



# **Ejercicio 4**

*Investigue y realice ejemplos que utilicen funciones para manipular elementos de arreglos (append, insert, delete, etc.) y arreglos entre sí (vstack, hstack, contacenate, etc.)*


In [58]:
lista = ['casa', 'auto', 'compu']
print('Lista original')
print(lista)

print()

# np.append(x, i) --> agrega el elemento i a la lista x
print('Lista con nuevo elemento')
np.append(lista, 'termo')
print(lista)

print()

# insert(i, x) --> agrega el elemento x en la posicion i
print('Lista con nuevo elemento')
np.insert(lista2, 'celu')
print(lista)

print()

# delete() --> elimina elemento
print('Elimina elemento de la lista')
lista.delete('celu')
print(lista)

print()




Lista original
['casa', 'auto', 'compu']

Lista con nuevo elemento
['casa', 'auto', 'compu']

Lista con nuevo elemento
['casa', 'auto', 'celu', 'compu']

Elimina elemento de la lista


AttributeError: ignored

# **BIBLIOTECA PANDAS**
---

### **Ejercicio 1**
*Investigue el funcionamiento del Dataframe de Pandas y cree uno con la información de la siguiente tabla:*

*Realice las siguientes operaciones:*

*● Imprimir los nombres de las columnas.*

*● Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia. Agregarlo de 2 formas diferentes.*

*● Eliminar de la tabla al Pedro repetido.*

*● Modificar los atributos de países que dicen “Peru” (sin acento) y reemplazarlos por “Perú” (con acento).*


In [ ]:
import pandas as pd

In [ ]:
nombre = ['Juan', 'María', 'Pedro', 'José']
edad = [20, 26, 18, 22]
pais = ['Argentina', 'Peru', 'Brasil', 'Chile']

In [ ]:
tabla = {'nombre' : nombre, 'edad' : edad, 'pais' : pais}

# creo el dataframe
df = pd.DataFrame(tabla)

In [ ]:
# muestro df
df
# como elimino la 1er columna?

nombre  edad       pais
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile

In [ ]:
#  Imprimir los nombres de las columnas.
print('Nombres de columnas: ')
print(tabla.keys())

Nombres de columnas: 
dict_keys(['nombre', 'edad', 'pais'])


In [ ]:
# Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia.
# Agregarlo de 2 formas diferentes

# agrego al final
#persona = {}
tabla.update({'nombre' : 'Pablo', 'edad' : 30, 'pais' : 'Colombia'})

# agrego en X lugar

In [ ]:
# muestro df
df

nombre  edad       pais
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile