<a href="https://colab.research.google.com/github/doloresgarro/Deep-Learning/blob/main/Practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **REPASO DE PYTHON**

---


### **Ejercicio 1**
*Utilizando los constructores para cada tipo de dato genere códigos de ejemplo y recórralos imprimiendo sus valores.*

In [ ]:
# lista
nums = [1, 2, 3, 4, 5]
# Imprimo lista
nums[:5]

[1, 2, 3, 4, 5]

In [ ]:
# tupla --> similar a una lista pero no se puede modificar elementos dentro de ella,
# se define entre ()
numsT = (1, 2, 3, 4, 5)
print(numsT) #imprime con ()
print(nums) # imprime con []

(1, 2, 3, 4, 5)
[1, 2, 3, 4, 5]


In [ ]:
# strings
palabras = "Hola Doloresssssssssss"
print(palabras)
print(len(palabras))
print(type(palabras))


Hola Doloresssssssssss
22
<class 'str'>


In [ ]:
# conjuntos
conj1 = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
conj2 = set([0, 2, 4, 6, 8,10, 12, 14, 16, 18, 20])

print('Conjunto 1')
print(conj1)
print('Conjunto 2')
print(conj2)
print()

# si cambio el orden o duplico un numero dentro del conjunto --> al imprimir está ordenado y no aparece el dato repetido
conj1 = set([1, 3, 5, 2, 6, 7, 4, 8, 9, 10])
conj2 = set([0, 2, 4, 4, 6, 8,10, 12, 14, 16, 18, 20])

print(conj1)
print(conj2)
print()

# elem que estan
print('Elementos que estan en el conj1 y no estan en el conj2')
print(conj1 - conj2) # --> elem q estan en el conj1 que no estan en el conj2


print('Elementos que estan en el conj2 y no estan en el conj1')
print(conj2 - conj1) # --> elem q estan en el conj2 que no estan en el conj1

# intersección --> elem q estan en ambos conjuntos
print('Intersección')
print(conj1 & conj2)

# union --> elems de ambos conjuntos
print('Unión')
print(conj1 | conj2)


Conjunto 1
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
Conjunto 2
{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20}

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20}

Elementos que estan en el conj1 y no estan en el conj2
{1, 3, 5, 7, 9}
Elementos que estan en el conj2 y no estan en el conj1
{0, 12, 14, 16, 18, 20}
Intersección
{2, 4, 6, 8, 10}
Unión
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20}


In [ ]:
# diccionario
persona = {'Nombre' : 'Dolores', 'Apellido' : 'Garro', 'Edad' : 23}

print('El nombre de la persona es: ')
print(persona['Nombre'])

print('Garro' in persona) # da falso porque busca una key
print('Apellido' in persona)

print(len(persona))

El nombre de la persona es: 
Dolores
False
True
3


### **Ejercicio 2**
*Genere el código necesario para recorrer simultáneamente 2 listas con la misma cantidad de elementos e imprima los mismos utilizando un único for (tip: función zip).*


In [ ]:
lista1 = [1, 2, 3]
lista2 = ['Juan', 'Valentina', 'Dolores']

list(zip(lista1, lista2))

[(1, 'Juan'), (2, 'Valentina'), (3, 'Dolores')]

### **Ejercicio 3**

*Implemente una función que a partir de la lista que recibe cómo parámetro, retorne una nueva lista sin elementos
repetidos. Compruebe su correcto funcionamiento.*


In [ ]:
def funcion(l1):
  l2 = list(set(l1)) #convierto en conjunto --> creo q primero convierte l1 en conjunto y dsp lo vuelve a convertir a lista
  return l2

In [ ]:
l1 = [1, 3, 3, 4]
print(l1)

print('Sin repetidos: ')
print(funcion(l1))




[1, 3, 3, 4]
Sin repetidos: 
[1, 3, 4]


### **Ejercicio 4**
*Implemente una función que calcule la distancia entre 2 puntos (2D). Utilice la función sqrt del paquete math para
implementarla y compruebe el correcto funcionamiento de la misma.*


In [ ]:
import math
x1 = 4 # esta bien sin guardar cada punto en una lista?
x2 = 2
y1 = 4
y2 = 2
d = math.sqrt(((x1-x2)**2)+((y1-y2)**2))
print(d)

2.8284271247461903


### **Ejercicio 5**
*Investigue y escriba código que demuestre el funcionamiento de los “slices” en listas*

In [ ]:
numeros = [8, 10, 4, 7, 3, 3, 23, 9]
print(numeros[:8]) #imprime todos elementos
print(numeros[:])
print(numeros[3:6]) #imprime elementos desde pos 3 hasta pos 5
print(numeros[0:4])

[8, 10, 4, 7, 3, 3, 23, 9]
[8, 10, 4, 7, 3, 3, 23, 9]
[7, 3, 3]
[8, 10, 4, 7]


# **BIBLIOTECA NUMPY**
---

# **Ejercicio 1**


*Practique la creación de vectores, matrices y tensores y responda:*

------------------------------------

*● ¿Qué diferencias hay entre los constructores, array, empty, full, zeros, ones, identity?*

**array** --> crea un array a partir de la lista o tupla lista y devuelve una referencia a el.

**empty** --> crea y devuelve una referencia a un array vacío

**full** --> crea y devuelve una referencia a un array cuyos elementos son todos valor.

**zeros** --> crea y devuelve una referencia a un array cuyos elems son todos ceros.

**ones** --> crea y devuelve una referencia a un array cuyos elems son todos unos.


**identity** -->  Crea y devuelve una referencia a la matriz identidad.


----------------------------------------


*● ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por defecto?¿Es siempre el mismo?*

Los tipos de datos que pueden utilizarse son --> int, float, complex
El tipo de dato que se toma por defecto es el float.

----------------------------------

*● ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?*
- np.randint(a,b) --> devuelve un número entero comprendido entre a y b (ambos inclusive) de forma aleatoria.

- np.randrange(a,b,salto) --> genera números enteros aleatorios comprendidos entre a y b separados entre sí con un salto.

- np.random() --> devuelve un float comprendido entre [0.0 y 1.0)

- np.uniform(a,b) --> devuelve un float aleatorio comprendido entre a y b (ambos inclusive).

- np.sample(conjunto, n) --> Esta función devuelve n elementos aleatorios de la secuencia conjunto

In [1]:
import numpy as np

In [5]:
# creo e imprimo vector
v = np.array([1, 2, 3])
print('vector: ')
print (v)

print()

# creo e imprimo matriz
m = np.array([(1, 2, 3), (4, 5, 6)])
print('matriz: ')
print(m)



vector: 
[1 2 3]

matriz: 
[[1 2 3]
 [4 5 6]]


# **Ejercicio 2**

Investigue y ejemplifique las funciones relacionadas al tamaño de los arrays de Numpy:

● ¿Para qué sirven las funciones shape, len, ndim, size?

● ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por defecto?¿Es siempre el mismo?

● ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?

# **BIBLIOTECA PANDAS**
---

### **Ejercicio 1**
*Investigue el funcionamiento del Dataframe de Pandas y cree uno con la información de la siguiente tabla:*

*Realice las siguientes operaciones:*

*● Imprimir los nombres de las columnas.*

*● Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia. Agregarlo de 2 formas diferentes.*

*● Eliminar de la tabla al Pedro repetido.*

*● Modificar los atributos de países que dicen “Peru” (sin acento) y reemplazarlos por “Perú” (con acento).*


In [ ]:
import pandas as pd

In [ ]:
nombre = ['Juan', 'María', 'Pedro', 'José']
edad = [20, 26, 18, 22]
pais = ['Argentina', 'Peru', 'Brasil', 'Chile']

In [ ]:
tabla = {'nombre' : nombre, 'edad' : edad, 'pais' : pais}

# creo el dataframe
df = pd.DataFrame(tabla)

In [ ]:
# muestro df
df
# como elimino la 1er columna?

nombre  edad       pais
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile

In [ ]:
#  Imprimir los nombres de las columnas.
print('Nombres de columnas: ')
print(tabla.keys())

Nombres de columnas: 
dict_keys(['nombre', 'edad', 'pais'])


In [ ]:
# Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia.
# Agregarlo de 2 formas diferentes

# agrego al final
#persona = {}
tabla.update({'nombre' : 'Pablo', 'edad' : 30, 'pais' : 'Colombia'})

# agrego en X lugar

In [ ]:
# muestro df
df

nombre  edad       pais
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile