<a href="https://colab.research.google.com/github/doloresgarro/Deep-Learning/blob/main/Pr%C3%A1ctica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica 4 - Deep Learning**
*Multiperceptrón*

# **Ejercicio 1**

*a) En base a esta información, indique:*

*▪ Cuántos ejemplos se utilizaron en el entrenamiento.*


*▪ Cuántas clases puede reconocer este multiperceptrón.*

*▪ Cuál es la precisión (accuracy) de la red sobre el conjunto de ejemplos completo.*

*▪ Cuáles son los valores de precisión de la red al responder por cada uno de los valores de clase (precision).*

*▪ Cuáles son los valores de sensibilidad de la red al responder por cada uno de los valores de clase (recall).*

*Se entreno una red neuronal multiperceptrón para resolver un problema de clasificación y al medir su desempeño sobre el conjunto de datos de entrenamiento se obtuvo la siguiente matriz de confusión:*

In [ ]:
import pandas as pd      # para trabajar con archivos de datos csv, excel, etc: https://pandas.pydata.org/docs/getting_started/tutorials.html
import numpy as np

# calcula las metricas precision, recall, f1-score y accuracy a partir de la matriz de confusion
# retorna tupla: ( precision, recall, f1_score, accuracy )
def calcular_metricas(conf_mat):
    precision = np.zeros(conf_mat.shape[0])  # inicializa en 0 el vector precisión, conf_mat.shape[0] --> indica el num de filas de la matriz con_mat
                                             # por lo tanto precisión va a ser una vector inicializado en 0 con el num de filas de la matriz recibida como parámetro
    for i in range(0, len(conf_mat)):
        precision[i] = conf_mat[i][i]/sum(conf_mat.T[i])  # en c/ pos divide el valor de la matriz en esa f y c por la suma de todos los elem de la matriz en la columna i

    recall = np.zeros(conf_mat.shape[0])   # recall lo mismo q lo anterior
    for i in range(0, len(conf_mat)):
        recall[i] = conf_mat[i][i]/sum(conf_mat[i])

    f1_score = 2* (precision*recall) /(precision+recall)

    accuracy =  0
    for i in range(0, len(conf_mat)):
        accuracy+=conf_mat[i][i]
    accuracy/= conf_mat.sum()        # conf_mat.sum() --> suma de elems de la matriz conf_mat

    return ( precision, recall, f1_score, accuracy )

# el parámetro metricas es una tupla ( precision, recall, f1_score, accuracy )
def imprimir_metricas( metricas ):
    (precision, recall, f1_score, accuracy) = metricas
    print('\n clase   precision    recall    f1-score')
    for i in range(0, len(precision)):
        print('%5d %10.2f %10.2f %10.2f' % (i, precision[i], recall[i], f1_score[i]))
    print('\naccuracy: %6.2f\n' % accuracy)



In [ ]:
confusion = np.array([
           [ 17, 0, 1, 0, 1 ],
           [ 0, 12, 0, 0, 0 ],
           [ 0, 0, 12, 0, 0 ],
           [ 2, 0, 0, 38, 0 ],
           [ 0, 8, 0, 0, 61 ]
           ])

print('\n Matriz de Confusión:')
print(confusion, '\n')



#calcula métricas de forma manual
metricas = calcular_metricas(confusion)
imprimir_metricas(metricas)






 Matriz de Confusión:
[[17  0  1  0  1]
 [ 0 12  0  0  0]
 [ 0  0 12  0  0]
 [ 2  0  0 38  0]
 [ 0  8  0  0 61]] 


 clase   precision    recall    f1-score
    0       0.89       0.89       0.89
    1       0.60       1.00       0.75
    2       0.92       1.00       0.96
    3       1.00       0.95       0.97
    4       0.98       0.88       0.93

accuracy:   0.92



Precisión --> proporción de predicciones correctas sobre una clase

Recall --> proporción de ejemplos de una clase que correctamente clasificados

Acurrancy --> cantidad de aciertos sobre el total de ejemplos


b) La clase con mejor valor de F1-score es la clase 3